version: '3.8'

networks:
  dvwa-network:
    driver: bridge
    attachable: true

services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    hostname: dvwa
    ports:
      - "80:80"
    networks:
      - dvwa-network

  splunk-receiver07:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: splunk-receiver07
    hostname: splunk-receiver07
    restart: unless-stopped
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD:-daethyradefault}
    ports:
      - 8000:8000
      - 8089:8089
    networks:
      dvwa-network:
        aliases:
          - receiver
    depends_on:
      - dvwa