version: '3.8'

services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "80:80"
    networks:
      - dvwa-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - /home/kali/.config/ngrok/ngrok.yml:/etc/ngrok.yml # path to your ngrok config file
    ports:
      - 4040:4040 # exposes ngrok dashboard
    networks:
      - dvwa-network
    depends_on:
      - dvwa
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  dvwa-network:
    driver: bridge