version: '3.8'

volumes:
  dvwa:

networks:
  dmz:
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      # Persist the database to avoid reinitialization each build
      - dvwa:/var/lib/mysql
    networks:
      dmz:
        ipv4_address: 172.20.0.2
    restart: unless-stopped

  dvwa:
    build: .
    image: vulnerables/web-dvwa
    pull_policy: build
    container_name: dvwa
    hostname: dvwa
    environment:
      - DB_SERVER=db
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD:-daethyradefault}
    networks:
      dmz:
        ipv4_address: 172.20.0.3
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - db

  splunk-receiver:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: splunk-receiver
    hostname: splunk-receiver
    restart: unless-stopped
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD:-daethyradefault}
    ports:
      - 8000:8000 # web dashboard
      - 8089:8089 # listen for forwarders
    networks:
      dmz:
        ipv4_address: 172.20.0.4
    depends_on:
      - dvwa