version: '3.8'

networks:
  dvwa-network:
    driver: bridge
    attachable: true

services:
  dvwa:
    #image: vulnerables/web-dvwa
    build: .
    container_name: dvwa
    hostname: dvwa
    ports:
      - "80:80"
    networks:
      - dvwa-network
    volumes:
      - ./config:/tmp/config
      - /home/kali/Desktop/hacklabs/Splunk-DVWA/splunkforwarder-9.2.1-78803f08aabb-linux-2.6-amd64.deb:/tmp/splunkforwarder-9.2.1-78803f08aabb-linux-2.6-amd64.deb
      - ./install_splunk_forwarder.sh:/tmp/install_splunk_forwarder.sh
    #command: sh -c "/tmp/install_splunk_forwarder.sh"

  splunk-receiver:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: splunk-receiver
    hostname: splunk-receiver
    restart: unless-stopped
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD:-daethyradefault}
    ports:
      - 8000:8000 # web dashboard
      - 8089:8089 # listen for forwarders
    networks:
      dvwa-network:
    depends_on:
      - dvwa