version: '3.8'

volumes:
  dvwa:

networks:
  dvwa-network:
    driver: bridge
    attachable: true

services:
  dvwa:
    build: .
    image: vulnerables/web-dvwa
    pull_policy: build
    container_name: dvwa
    hostname: dvwa
    environment:
      - DB_SERVER=db
    networks:
      - dvwa-network
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - db
  
  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      # Persist the database to avoid reinitialization each build
      - dvwa:/var/lib/mysql
    networks:
      - dvwa-network
    restart: unless-stopped

  splunk-receiver:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: splunk-receiver
    hostname: splunk-receiver
    restart: unless-stopped
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD:-daethyradefault}
    ports:
      - 8000:8000 # web dashboard
      - 8089:8089 # listen for forwarders
    networks:
      dvwa-network:
    depends_on:
      - dvwa